<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Module 4: Spatial Regression and Epidemiological Risk Factor Analysis – Spatial Epidemiology in R: A Hands-On Tutorial</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-ml.html" rel="next">
<link href="./03-autocorrelation.html" rel="prev">
<link href="./Spat_epi.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-regression.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Module 4: Spatial Regression and Epidemiological Risk Factor Analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Spatial Epidemiology in R: A Hands-On Tutorial</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/gkagyen/spatial-epi-tutorial" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R Environment Setup and Spatial Data Import</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-mapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Module 2: Disease Mapping in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-autocorrelation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Module 3: Spatial Autocorrelation and Cluster Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Module 4: Spatial Regression and Epidemiological Risk Factor Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-ml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Module 5: Machine Learning for Spatial Epidemiology (Showcasing <code>mlspatial</code>)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-integration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Module 6: Integrated Application from Data to Decision</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-simulate" id="toc-sec-simulate" class="nav-link active" data-scroll-target="#sec-simulate"><span class="header-section-number">4.1</span> Simulate Risk-Factor Covariates</a></li>
  <li><a href="#sec-ols" id="toc-sec-ols" class="nav-link" data-scroll-target="#sec-ols"><span class="header-section-number">4.2</span> Build Ordinary Least Squares (OLS) Regression</a></li>
  <li><a href="#sec-diagnose" id="toc-sec-diagnose" class="nav-link" data-scroll-target="#sec-diagnose"><span class="header-section-number">4.3</span> Diagnosing Data Leakage</a></li>
  <li><a href="#sec-ols-refine" id="toc-sec-ols-refine" class="nav-link" data-scroll-target="#sec-ols-refine"><span class="header-section-number">4.4</span> Refined Model</a></li>
  <li><a href="#sec-residual-moran" id="toc-sec-residual-moran" class="nav-link" data-scroll-target="#sec-residual-moran"><span class="header-section-number">4.5</span> Test for Spatial Residual Autocorrelation</a></li>
  <li><a href="#sec-gwr" id="toc-sec-gwr" class="nav-link" data-scroll-target="#sec-gwr"><span class="header-section-number">4.6</span> Geographically Weighted Regression (GWR)</a></li>
  <li><a href="#sec-gwr-viz" id="toc-sec-gwr-viz" class="nav-link" data-scroll-target="#sec-gwr-viz"><span class="header-section-number">4.7</span> Interpret and Visualize GWR Results</a></li>
  <li><a href="#sec-m4-check" id="toc-sec-m4-check" class="nav-link" data-scroll-target="#sec-m4-check">Module 4 Checklist</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-module4" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Module 4: Spatial Regression and Epidemiological Risk Factor Analysis</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This module connects health outcomes to lifestyle/genetic drivers. You will simulate covariates, build a global OLS model, test its residuals for spatial autocorrelation, and then fit a Geographically Weighted Regression (GWR) to capture spatially varying relationships.</p>
<hr>
<section id="sec-simulate" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="sec-simulate"><span class="header-section-number">4.1</span> Simulate Risk-Factor Covariates</h2>
<p><strong>Purpose:</strong> Link health outcomes to known epidemiological risk factors for pancreatic cancer (smoking, obesity, diabetes, alcohol use, family history urbanisation) for use in spatial regression exercise</p>
<p>For this tutorial, we <strong>simulate</strong> six covariates directly at the country level so the code is fully runnable without downloading external datasets. Because <code>africa_health</code> is a polygon layer where each row already represents one country (like <code>incidence</code>, <code>TOTPOP</code> etc), we do not need a raster data - we can generate one random value per row and append it directly with <code>mutate()</code></p>
<p><strong>In real research</strong>, replace these random draws with actual country-level estimates from sources such as the WHO Global Health Observatory (smoking, obesity, diabetes prevalence), IARC GLOBOCAN risk-factor tables, or national health surveys. These are typically small CSV/Excel downloads, joined to <code>africa_health</code> by country ISO code (<code>ISO_3DIGIT</code>) rather than simulated.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">898</span>)  <span class="co"># reproducibility</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(africa_health)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>africa_health <span class="ot">&lt;-</span> africa_health <span class="sc">|&gt;</span> </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Smoking prevalence (% of adult population) — WHO African region estimates</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># typically range ~10-25%; strongest modifiable risk factor for pancreatic cancer</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">smoking_prev =</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">8</span>, <span class="at">max =</span> <span class="dv">28</span>), <span class="dv">1</span>),</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Obesity prevalence (% adults, BMI &gt;= 30) — WHO Africa region estimates</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># range roughly 5-30% depending on urbanization/country</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">obesity_prev =</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">5</span>, <span class="at">max =</span> <span class="dv">30</span>), <span class="dv">1</span>),</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Type 2 diabetes prevalence (%) — longstanding diabetes is a well-established</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># pancreatic cancer risk factor; IDF Africa estimates ~3-10% typically</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">diabetes_prev =</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">2</span>, <span class="at">max =</span> <span class="dv">11</span>), <span class="dv">1</span>),</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Alcohol consumption (litres pure alcohol per capita per year) —</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># heavy long-term use linked to chronic pancreatitis -&gt; elevated risk</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">alcohol_per_capita =</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="at">min =</span> <span class="fl">0.5</span>, <span class="at">max =</span> <span class="dv">12</span>), <span class="dv">1</span>),</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Family history / genetic predisposition proxy (% of cases with</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    <span class="co"># first-degree relative history) — literature suggests ~5-10% of</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    <span class="co"># pancreatic cancers have a hereditary component</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">family_history_prev =</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">3</span>, <span class="at">max =</span> <span class="dv">10</span>), <span class="dv">1</span>),</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Urbanization (%) — proxy for dietary/lifestyle transition,</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    <span class="co"># often used as a covariate for NCD risk in African epidemiology</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">urbanization_pct =</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">15</span>, <span class="at">max =</span> <span class="dv">85</span>), <span class="dv">1</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(africa_health[<span class="fu">c</span>(<span class="st">"NAME"</span>, <span class="st">"smoking_prev"</span>, <span class="st">"obesity_prev"</span>, </span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"diabetes_prev"</span>, <span class="st">"alcohol_per_capita"</span>, </span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"family_history_prev"</span>, <span class="st">"urbanization_pct"</span>)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 7 fields
Geometry type: GEOMETRY
Dimension:     XY
Bounding box:  xmin: -2823124 ymin: 484116 xmax: 266936 ymax: 1943229
Projected CRS: WGS 84 / Pseudo-Mercator
           NAME smoking_prev obesity_prev diabetes_prev alcohol_per_capita
1  Burkina Faso         13.6         13.7           7.0                2.9
2    Cabo Verde         24.1          6.6           4.3                1.5
3 Cote d'Ivoire         17.3         26.3           4.0                8.6
4        Gambia         20.1          9.9           8.2                8.6
5         Ghana         17.1         11.5           3.1                6.4
6        Guinea         27.4         10.8           5.7               10.4
  family_history_prev urbanization_pct                       geometry
1                 9.7             73.2 POLYGON ((102188.3 1231699,...
2                 6.7             54.2 MULTIPOLYGON (((-2721438 16...
3                 9.2             45.8 MULTIPOLYGON (((-350501.5 5...
4                 3.9             68.4 POLYGON ((-1848987 1513709,...
5                 7.8             49.0 POLYGON ((-352664.2 697837....
6                 3.4             69.4 POLYGON ((-884637.8 895544....</code></pre>
</div>
</div>
<p><strong>Key parameters:</strong> - <code>runif(n, min, max)</code>: draws <code>n</code> random values from a uniform distribution bounded to a realistic range for each covariate, loosely based on published prevalence ranges across African countries.</p>
<p>These covariates are simulated <strong>independently of <code>incidence</code> and of each other</strong> — they are not designed to correlate with pancreatic cancer rates. This is intentional: the goal is to demonstrate the spatial regression <em>pipeline</em> (data structure, model syntax, diagnostics), not to produce a real epidemiological finding.</p>
<p><strong>Expected output:</strong> Six new columns appended to <code>africa_health</code></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Column</th>
<th>Description</th>
<th>Simulated range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>smoking_prev</code></td>
<td>Adult smoking prevalence (%)</td>
<td>8–28%</td>
</tr>
<tr class="even">
<td><code>obesity_prev</code></td>
<td>Adult obesity prevalence, BMI ≥ 30 (%)</td>
<td>5–30%</td>
</tr>
<tr class="odd">
<td><code>diabetes_prev</code></td>
<td>Type 2 diabetes prevalence (%)</td>
<td>2–11%</td>
</tr>
<tr class="even">
<td><code>alcohol_per_capita</code></td>
<td>Alcohol consumption (litres pure alcohol/year)</td>
<td>0.5–12</td>
</tr>
<tr class="odd">
<td><code>family_history_prev</code></td>
<td>Cases with first-degree relative history (%)</td>
<td>3–10%</td>
</tr>
<tr class="even">
<td><code>urbanization_pct</code></td>
<td>Urban population (%)</td>
<td>15–85%</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="sec-ols" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="sec-ols"><span class="header-section-number">4.2</span> Build Ordinary Least Squares (OLS) Regression</h2>
<p><strong>Purpose:</strong> Establish a global (non-spatial) baseline model relating pancreatic cancer incidence to lifestyle, genetic and demographic risk factors.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>ols_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  incidence <span class="sc">~</span> smoking_prev <span class="sc">+</span> obesity_prev <span class="sc">+</span> diabetes_prev <span class="sc">+</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    alcohol_per_capita <span class="sc">+</span> family_history_prev <span class="sc">+</span> urbanization_pct <span class="sc">+</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    female <span class="sc">+</span> male <span class="sc">+</span> ageb <span class="sc">+</span> agec,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> africa_health</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ols_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = incidence ~ smoking_prev + obesity_prev + diabetes_prev + 
    alcohol_per_capita + family_history_prev + urbanization_pct + 
    female + male + ageb + agec, data = africa_health)

Residuals:
       Min         1Q     Median         3Q        Max 
-1.601e-12 -1.500e-13  2.316e-14  2.169e-13  7.935e-13 

Coefficients:
                      Estimate Std. Error    t value Pr(&gt;|t|)    
(Intercept)         -2.950e-13  4.884e-13 -6.040e-01 0.549105    
smoking_prev        -1.345e-14  1.124e-14 -1.196e+00 0.238171    
obesity_prev        -6.195e-16  9.145e-15 -6.800e-02 0.946304    
diabetes_prev        6.421e-14  3.072e-14  2.090e+00 0.042536 *  
alcohol_per_capita  -9.800e-15  2.052e-14 -4.780e-01 0.635292    
family_history_prev -1.106e-14  2.899e-14 -3.820e-01 0.704643    
urbanization_pct    -4.111e-16  3.459e-15 -1.190e-01 0.905951    
female               9.302e-02  9.252e-15  1.005e+13  &lt; 2e-16 ***
male                 9.302e-02  9.279e-15  1.003e+13  &lt; 2e-16 ***
ageb                 3.896e-14  9.366e-15  4.160e+00 0.000149 ***
agec                 3.865e-14  9.251e-15  4.178e+00 0.000141 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.452e-13 on 43 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 2.36e+31 on 10 and 43 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Key parameters:</strong> - Formula syntax: <code>response ~ predictor1 + predictor2 + ...</code> - Interpretation: Positive coefficients indicate higher expected incidence with higher predictor values.</p>
<p><strong>Expected output:</strong> A standard <code>lm</code> summary showing coefficients, standard errors, t-values, and p-values. R² indicates the proportion of variance explained globally.</p>
<p>This model prints a warning message. The <span class="math inline">\(R^2\)</span> value is exactly <strong>1</strong> which creates room for concern. This is not a real spatial regression breakthrough, it is a classic case of data leakage through an identity relationship. Hence the perfect fit is a red flag not a good sign.</p>
<hr>
</section>
<section id="sec-diagnose" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="sec-diagnose"><span class="header-section-number">4.3</span> Diagnosing Data Leakage</h2>
<p>The first <strong>ols</strong> model returned <code>R-squared: 1</code>, an F-statistic of <code>2.36e+31</code> and an explicit warning - <code>essentialperfect fit: summary may be unreliable</code>. A model that fits perfectly is almost always telling you that the outcome is mathematically derived from one or more of its own predictors. This is called <strong>data leakage</strong></p>
<p><strong>Step 1: Inspect the coefficients.</strong> Looking at the model summary, two variables stood out immediately:</p>
<pre><code>female   9.302e-02   t = 1.005e+13   p &lt; 2e-16
male     9.302e-02   t = 1.003e+13   p &lt; 2e-16</code></pre>
<p>Both coefficients are identical to four decimal figures, with t-value around <span class="math inline">\(10^{13}\)</span>. T-values that enormous are a signature of the model detecting an algebraic identity not a strong effect.</p>
<p><strong>Step 2: Test the suspected Identity directly</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(africa_health<span class="sc">$</span>incidence, africa_health<span class="sc">$</span>female <span class="sc">+</span> africa_health<span class="sc">$</span>male)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(africa_health<span class="sc">$</span>incidence <span class="sc">/</span> (africa_health<span class="sc">$</span>female <span class="sc">+</span> africa_health<span class="sc">$</span>male))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.09302326 0.09302326 0.09302326 0.09302326 0.09302326 0.09302326</code></pre>
</div>
</div>
<p>A correlation of 1 between <code>incidence</code> and gender confirms that <code>incidence</code> is a fixed linear function of <code>female + male</code>. Dividing one by the other reveals the exact relationship. Every single country returns the exact constant <code>0.09302326</code>, meaning <code>incidence</code> was computed directly from <code>male</code> and <code>female</code> (or they share a common upstream calculation)</p>
<p>Including <code>male</code> and <code>female</code> as predictors makes it <strong>mathematically circular</strong>, the model is not learning but rather reversing an arithmetic formula.</p>
<p><strong>Step 3: Screen every numeric variable for leakage</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check all numeric columns systematically against incidence</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>numeric_cols <span class="ot">&lt;-</span> africa_health <span class="sc">|&gt;</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span>                    <span class="co"># drop geometry — not numeric</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">|&gt;</span> </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>incidence) <span class="sc">|&gt;</span>                    <span class="co"># exclude the outcome itself</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>()</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>cor_check <span class="ot">&lt;-</span> <span class="fu">sapply</span>(numeric_cols, <span class="cf">function</span>(col) {</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(africa_health<span class="sc">$</span>incidence, africa_health[[col]], <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">abs</span>(cor_check), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               agec                ageb                 yra                 yrb 
        0.999776035         0.997363274         0.994162603         0.993023880 
                yrd               mageb                 yrc                male 
        0.991366013         0.991300624         0.991276110         0.990157443 
                yre               magec               fageb              female 
        0.989764734         0.987751703         0.985364466         0.982334295 
              fagec               magea                agea               fagea 
        0.979661775         0.863353711         0.751522574         0.594702968 
             TOTPOP       diabetes_prev            OBJECTID        obesity_prev 
        0.568333472         0.195570160         0.190926164         0.134111883 
family_history_prev  alcohol_per_capita    urbanization_pct        smoking_prev 
        0.120046661         0.082419609         0.017524733         0.005253558 </code></pre>
</div>
</div>
<p>The output shows the leakage extends well beyond <code>female</code>/<code>male</code>. Almost every variable with <code>|r|&gt;0.85</code> shares a consistent naming pattern: age-banded (<code>age*</code>), year-indexed (<code>yr*</code>) and male/female-stratified (<code>m*</code>/<code>f*</code>). This strongly indicates they are all components of the same underlying case-count calculation that produced <code>incidence</code>.</p>
<hr>
</section>
<section id="sec-ols-refine" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="sec-ols-refine"><span class="header-section-number">4.4</span> Refined Model</h2>
<p>Based on the correlation screen, we exclude every variable structurally tied to incidence calculation along with the non-informative row identifier. In their place we retain our six simulated risk-factor covariates.</p>
<p>Another thing worth mentioning in epidemiology is the raw incidence counts. We rarely run models on raw count data. Instead we will calculate an <strong>incidence rate</strong> (e.g cases per 100,000 people) before modelling.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>africa_health <span class="ot">&lt;-</span> africa_health <span class="sc">|&gt;</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">incidence_rate =</span> (incidence<span class="sc">/</span>TOTPOP)<span class="sc">*</span><span class="dv">100000</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>ols_refined <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  incidence_rate <span class="sc">~</span> smoking_prev <span class="sc">+</span> obesity_prev <span class="sc">+</span> diabetes_prev <span class="sc">+</span> </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    alcohol_per_capita <span class="sc">+</span> family_history_prev <span class="sc">+</span> urbanization_pct,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> africa_health</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ols_refined)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = incidence_rate ~ smoking_prev + obesity_prev + diabetes_prev + 
    alcohol_per_capita + family_history_prev + urbanization_pct, 
    data = africa_health)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.9009 -1.5714 -0.7732  0.8217  8.7829 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)          9.33286    3.00583   3.105  0.00322 **
smoking_prev         0.02596    0.07047   0.368  0.71426   
obesity_prev        -0.10385    0.05500  -1.888  0.06520 . 
diabetes_prev       -0.17452    0.18733  -0.932  0.35628   
alcohol_per_capita  -0.17127    0.12655  -1.353  0.18241   
family_history_prev -0.08952    0.17952  -0.499  0.62036   
urbanization_pct    -0.04129    0.02130  -1.938  0.05859 . 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.807 on 47 degrees of freedom
Multiple R-squared:  0.1502,    Adjusted R-squared:  0.04166 
F-statistic: 1.384 on 6 and 47 DF,  p-value: 0.2408</code></pre>
</div>
</div>
<p>This output provides an overall statistically insignificant model. Because the simulated covariates were generated purely as random noise (<code>runif</code>), the OLS model did exactly what it is supposed to do. It shows no statistical relationship between these covariates and the target variable.</p>
<p>Although all the covariates are randomly generated, <code>obesity_prev</code> and <code>urbanization_pct</code> are showing marginal significance. This is purely by chance because we can confirm from their estimate direction (<code>-0.103</code> and <code>-0.041</code>) that the math contradicts the biology; higher obesity and urbanisation should increase pancreatic cancer risk.</p>
<hr>
</section>
<section id="sec-residual-moran" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="sec-residual-moran"><span class="header-section-number">4.5</span> Test for Spatial Residual Autocorrelation</h2>
<p><strong>Purpose:</strong> Check whether the OLS model’s residuals are spatially random. The core assumption of OLS is that its errors (residuals) are randomly distributed. If significant autocorrelation remains, OLS standard errors are biased and a spatial model (or GWR) is needed.</p>
<p>In spatial epidemiology, if our model is missing a key geographical variable, the model’s error will cluster together geographically. This is called <strong>Spatial Autocorrelation of Residuals</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>residual_moran <span class="ot">&lt;-</span> <span class="fu">lm.morantest</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> ols_refined,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">listw =</span> lw,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">zero.policy =</span> <span class="cn">TRUE</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(residual_moran)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Global Moran I for regression residuals

data:  
model: lm(formula = incidence_rate ~ smoking_prev + obesity_prev +
diabetes_prev + alcohol_per_capita + family_history_prev +
urbanization_pct, data = africa_health)
weights: lw

Moran I statistic standard deviate = 0.20896, p-value = 0.4172
alternative hypothesis: greater
sample estimates:
Observed Moran I      Expectation         Variance 
    -0.005685554     -0.027729069      0.011127988 </code></pre>
</div>
</div>
<p><strong>Key parameters:</strong> - <code>lm.morantest()</code>: Applies Moran’s I to the regression residuals rather than the raw outcome.</p>
<p><strong>Expected output:</strong> - If p &lt; 0.05, residuals are spatially autocorrelated → OLS is misspecified, therefore a spatial model (like GWR) is required. - If p &gt; 0.05, OLS residuals are spatially random (rare in epidemiology).</p>
<p>The Null hypothesis for this test is that the residuals are randomly distributed (no spatial autocorrelation). Because our p-vale is high, we conclude that the errors in the model are randomly distributed across the African continent. There is no statistically significant spatial autocorrelation in the residuals.</p>
<hr>
</section>
<section id="sec-gwr" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="sec-gwr"><span class="header-section-number">4.6</span> Geographically Weighted Regression (GWR)</h2>
<p><strong>Purpose:</strong> Fit local regression models that allow the relationship between cancer and lifestyle/genetic risk factors to vary across space (spatial non-stationarity).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Find optimal adaptive bandwidth (number of nearest neighbours)</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># This uses cross-validation to find best fit</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>bw_adapt <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> incidence_rate <span class="sc">~</span> smoking_prev <span class="sc">+</span> obesity_prev <span class="sc">+</span> </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    diabetes_prev <span class="sc">+</span> alcohol_per_capita <span class="sc">+</span> </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    family_history_prev <span class="sc">+</span> urbanization_pct,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> africa_health,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">approach =</span> <span class="st">"CV"</span>,     <span class="co"># Cross-validation approach</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">kernel =</span> <span class="st">"bisquare"</span>, <span class="co"># the shape of the spatial weight decay</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">adaptive =</span> <span class="cn">TRUE</span>      <span class="co"># TRUE=find optimal no. of neigbours. FALSE = find distance</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Adaptive bandwidth: 41 CV score: 476.0228 
Adaptive bandwidth: 33 CV score: 463.883 
Adaptive bandwidth: 28 CV score: 472.4997 
Adaptive bandwidth: 36 CV score: 464.0033 
Adaptive bandwidth: 31 CV score: 466.1091 
Adaptive bandwidth: 34 CV score: 463.8069 
Adaptive bandwidth: 35 CV score: 463.2405 
Adaptive bandwidth: 35 CV score: 463.2405 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Optimal adaptive bandwidth:"</span>, bw_adapt, <span class="st">"neighbors</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimal adaptive bandwidth: 35 neighbors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Fit GWR model</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>gwr_model <span class="ot">&lt;-</span> <span class="fu">gwr.basic</span>(</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> incidence_rate <span class="sc">~</span> smoking_prev <span class="sc">+</span> obesity_prev <span class="sc">+</span> </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    diabetes_prev <span class="sc">+</span> alcohol_per_capita <span class="sc">+</span> </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    family_history_prev <span class="sc">+</span> urbanization_pct,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> africa_health,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">bw =</span> bw_adapt,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">kernel =</span> <span class="st">"bisquare"</span>,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">adaptive =</span> <span class="cn">TRUE</span>,</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Print summary (includes global OLS + local GWR diagnostics)</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(gwr_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ***********************************************************************
   *                       Package   GWmodel                             *
   ***********************************************************************
   Program starts at: 2026-08-12 13:46:55.337658 
   Call:
   gwr.basic(formula = incidence_rate ~ smoking_prev + obesity_prev + 
    diabetes_prev + alcohol_per_capita + family_history_prev + 
    urbanization_pct, data = africa_health, bw = bw_adapt, kernel = "bisquare", 
    adaptive = TRUE)

   Dependent (y) variable:  incidence_rate
   Independent variables:  smoking_prev obesity_prev diabetes_prev alcohol_per_capita family_history_prev urbanization_pct
   Number of data points: 54
   ***********************************************************************
   *                    Results of Global Regression                     *
   ***********************************************************************

   Call:
    lm(formula = formula, data = data)

   Residuals:
    Min      1Q  Median      3Q     Max 
-3.9009 -1.5714 -0.7732  0.8217  8.7829 

   Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)   
   (Intercept)          9.33286    3.00583   3.105  0.00322 **
   smoking_prev         0.02596    0.07047   0.368  0.71426   
   obesity_prev        -0.10385    0.05500  -1.888  0.06520 . 
   diabetes_prev       -0.17452    0.18733  -0.932  0.35628   
   alcohol_per_capita  -0.17127    0.12655  -1.353  0.18241   
   family_history_prev -0.08952    0.17952  -0.499  0.62036   
   urbanization_pct    -0.04129    0.02130  -1.938  0.05859 . 

   ---Significance stars
   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
   Residual standard error: 2.807 on 47 degrees of freedom
   Multiple R-squared: 0.1502
   Adjusted R-squared: 0.04166 
   F-statistic: 1.384 on 6 and 47 DF,  p-value: 0.2408 
   ***Extra Diagnostic information
   Residual sum of squares: 370.3139
   Sigma(hat): 2.668599
   AIC:  273.2152
   AICc:  276.4152
   BIC:  267.0389
   ***********************************************************************
   *          Results of Geographically Weighted Regression              *
   ***********************************************************************

   *********************Model calibration information*********************
   Kernel function: bisquare 
   Adaptive bandwidth: 35 (number of nearest neighbours)
   Regression points: the same locations as observations are used.
   Distance metric: Euclidean distance metric is used.

   ****************Summary of GWR coefficient estimates:******************
                             Min.    1st Qu.     Median    3rd Qu.    Max.
   Intercept            2.5414463  5.7074985  7.2222933 10.3176946 15.2724
   smoking_prev        -0.1729309 -0.0182621  0.0121007  0.0870956  0.1121
   obesity_prev        -0.2135095 -0.1292391 -0.0950674 -0.0555409  0.0517
   diabetes_prev       -0.6432196 -0.2850108 -0.1078285  0.0331103  0.2252
   alcohol_per_capita  -0.5719018 -0.1832194 -0.1390848 -0.0851088  0.1293
   family_history_prev -0.2341325 -0.1174264 -0.0622756 -0.0099285  0.0802
   urbanization_pct    -0.0772384 -0.0509485 -0.0236476 -0.0171660 -0.0028
   ************************Diagnostic information*************************
   Number of data points: 54 
   Effective number of parameters (2trace(S) - trace(S'S)): 25.72294 
   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 28.27706 
   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 294.6998 
   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 239.3899 
   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 247.9558 
   Residual sum of squares: 180.6605 
   R-square value:  0.5853944 
   Adjusted R-square value:  0.1944111 

   ***********************************************************************
   Program stops at: 2026-08-12 13:46:55.364684 </code></pre>
</div>
</div>
<p><strong>Key parameters:</strong> - <code>bw.gwr()</code>: <code>adaptive = TRUE</code> finds a bandwidth in number of neighbours rather than distance units. Better for irregularly sized polygons. - <code>kernel = "bisquare"</code>: Weights drop to zero beyond the bandwidth, creating clean local windows. - <code>gwr.basic()</code>: Fits a separate weighted OLS at every polygon centroid.</p>
<p><strong>Expected output:</strong> - Bandwidth value (gave 35 neighbours for country-level Africa data). - GWR diagnostics showing local R², coefficient ranges, and AICc values vs global OLS.</p>
<p>A bandwidth of 35 is huge for a spatial region of 54 countries. The model is forced to look at over half a continent to make a single prediction. The GWR coefficient estimates are given as a range because it changes depending on where you are on the map. In the global OLS the relationship for <code>diabetes_pev</code> is negative but GWR reveals that it changes in some part of the continent (<code>min:-0.543</code> and <code>max:0.225</code>). This shows the relationship is unstable across space (But remember this is simulated data so the model is just chasing random noise).</p>
<p>The GWR <span class="math inline">\(R^2\)</span> looks very high but that should not be the metric of interest because it is almost always high for GWR analysis. The parameter of interest is the AICc (Lower is better). Even the the GWR artificially inflated the <span class="math inline">\(R^2\)</span>, the AICc actually went up from 276.4 in the OLS to 294.7, this tells us that the GWR model is statistically worse. The OLS errors were randomly distributed and so the GWR was completely unnecessary.</p>
<hr>
</section>
<section id="sec-gwr-viz" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="sec-gwr-viz"><span class="header-section-number">4.7</span> Interpret and Visualize GWR Results</h2>
<p><strong>Purpose:</strong> Map local coefficient surfaces to see <strong>where</strong> each predictor matters most.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gwr_model$SDF is an sf object containing local coefficients</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>gwr_sf <span class="ot">&lt;-</span> gwr_model<span class="sc">$</span>SDF</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Map the spatially varying coefficient for diabetes</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(gwr_sf) <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"diabetes_prev"</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill.scale =</span> <span class="fu">tm_scale_continuous</span>(</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">values =</span> <span class="st">"-brewer.rd_bu"</span>,     <span class="co"># Negative RdBu puts red at positive and Blue at negative</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">midpoint =</span> <span class="dv">0</span>          <span class="co"># Forces the white/neutral color to sit exactly at zero</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Local Coefficient</span><span class="sc">\n</span><span class="st">(Diabetes)"</span>),</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> <span class="st">'black'</span>,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">col_alpha =</span> <span class="fl">0.5</span>,        </span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">lwd =</span> <span class="fl">0.5</span>               </span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_title</span>(<span class="st">"GWR: Spatially Varying Effect of Diabetes"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regression_files/figure-html/gwr-maps-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Map the local model fit (Local R-squared)</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(gwr_sf) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Local_R2"</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill.scale =</span> <span class="fu">tm_scale_continuous</span>(</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">values =</span> <span class="st">"viridis"</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Local R-Squared"</span>),</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> <span class="st">"black"</span>,</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">lwd =</span> <span class="fl">0.5</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_title</span>(<span class="st">"GWR: Local Model Performance across Africa"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-regression_files/figure-html/gwr-maps-2.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key parameters:</strong> - <code>midpoint = 0</code> in <code>fill.scale = tm_scale_continuous()</code> centers the colour scale at zero, making positive (red) and negative (blue) effects immediately visible.</p>
<p><strong>Expected output:</strong> Two maps; one showing spatially varying coefficient <code>diabetes_prev</code> and the other showing the the area where the GWR model performs best (<code>Local R2</code>). Areas with red indicate a positive local association; blue indicates a negative local association for the <code>diabetes_prev</code> .</p>
<p>The spatial variation map shows smooth colour transitions across borders. Whiles this creates a beautiful map, remember our <strong>AICc</strong> score. Because the underlying data is purely random noise, this map is just a visualisation of the GWR algorithm ‘forcing’ a spatial pattern where none actually exists.</p>
<hr>
</section>
<section id="sec-m4-check" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="sec-m4-check">Module 4 Checklist</h2>
<ul class="task-list">
<li><label><input type="checkbox">Extracted environmental covariates from raster data</label></li>
<li><label><input type="checkbox">Built and interpreted an OLS regression model</label></li>
<li><label><input type="checkbox">Tested OLS residuals for spatial autocorrelation</label></li>
<li><label><input type="checkbox">Fitted a GWR model with adaptive bandwidth</label></li>
<li><label><input type="checkbox">Mapped local coefficient surfaces</label></li>
</ul>
<p><strong>Next:</strong> Proceed to <a href="./05-ml.html">Module 5: Machine Learning for Spatial Epidemiology</a>.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-autocorrelation.html" class="pagination-link" aria-label="Module 3: Spatial Autocorrelation and Cluster Analysis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Module 3: Spatial Autocorrelation and Cluster Analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-ml.html" class="pagination-link" aria-label="Module 5: Machine Learning for Spatial Epidemiology (Showcasing `mlspatial`)">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Module 5: Machine Learning for Spatial Epidemiology (Showcasing <code>mlspatial</code>)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb24" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="an">editor:</span><span class="co"> </span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co">  markdown: </span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co">    wrap: 72</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="fu"># Module 4: Spatial Regression and Epidemiological Risk Factor Analysis {#sec-module4}</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>This module connects health outcomes to lifestyle/genetic drivers. You</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>will simulate covariates, build a global OLS model, test its residuals</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>for spatial autocorrelation, and then fit a Geographically Weighted</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>Regression (GWR) to capture spatially varying relationships.</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup-m4}</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spdep)</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GWmodel)</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mlspatial)</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(africa_shp, <span class="at">package =</span> <span class="st">"mlspatial"</span>)</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(panc_incidence, <span class="at">package =</span> <span class="st">"mlspatial"</span>)</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>africa_health <span class="ot">&lt;-</span> <span class="fu">join_data</span>(</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>  africa_shp <span class="sc">|&gt;</span> <span class="fu">mutate</span>(</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">across</span>(<span class="fu">c</span>(NAME, COUNTRYAFF),</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>           <span class="sc">~</span> <span class="fu">replace_values</span>(.x, <span class="st">"Côte d'Ivoire"</span> <span class="sc">~</span> <span class="st">"Cote d'Ivoire"</span>))),</span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>  panc_incidence, <span class="at">by =</span> <span class="st">"NAME"</span></span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a>africa_health <span class="ot">&lt;-</span> <span class="fu">st_make_valid</span>(africa_health)</span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a>nb <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(africa_health, <span class="at">row.names =</span> africa_health<span class="sc">$</span>NAME, <span class="at">queen =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a>lw <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(nb, <span class="at">style =</span> <span class="st">"W"</span>, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a><span class="fu">## Simulate Risk-Factor Covariates {#sec-simulate}</span></span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a>**Purpose:** Link health outcomes to known epidemiological risk factors</span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a>for pancreatic cancer (smoking, obesity, diabetes, alcohol use, family</span>
<span id="cb24-44"><a href="#cb24-44" aria-hidden="true" tabindex="-1"></a>history urbanisation) for use in spatial regression exercise</span>
<span id="cb24-45"><a href="#cb24-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-46"><a href="#cb24-46" aria-hidden="true" tabindex="-1"></a>For this tutorial, we **simulate** six covariates directly at the</span>
<span id="cb24-47"><a href="#cb24-47" aria-hidden="true" tabindex="-1"></a>country level so the code is fully runnable without downloading external</span>
<span id="cb24-48"><a href="#cb24-48" aria-hidden="true" tabindex="-1"></a>datasets. Because <span class="in">`africa_health`</span> is a polygon layer where each row</span>
<span id="cb24-49"><a href="#cb24-49" aria-hidden="true" tabindex="-1"></a>already represents one country (like <span class="in">`incidence`</span>, <span class="in">`TOTPOP`</span> etc), we do</span>
<span id="cb24-50"><a href="#cb24-50" aria-hidden="true" tabindex="-1"></a>not need a raster data - we can generate one random value per row and</span>
<span id="cb24-51"><a href="#cb24-51" aria-hidden="true" tabindex="-1"></a>append it directly with <span class="in">`mutate()`</span></span>
<span id="cb24-52"><a href="#cb24-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-53"><a href="#cb24-53" aria-hidden="true" tabindex="-1"></a>**In real research**, replace these random draws with actual</span>
<span id="cb24-54"><a href="#cb24-54" aria-hidden="true" tabindex="-1"></a>country-level estimates from sources such as the WHO Global Health</span>
<span id="cb24-55"><a href="#cb24-55" aria-hidden="true" tabindex="-1"></a>Observatory (smoking, obesity, diabetes prevalence), IARC GLOBOCAN</span>
<span id="cb24-56"><a href="#cb24-56" aria-hidden="true" tabindex="-1"></a>risk-factor tables, or national health surveys. These are typically</span>
<span id="cb24-57"><a href="#cb24-57" aria-hidden="true" tabindex="-1"></a>small CSV/Excel downloads, joined to <span class="in">`africa_health`</span> by country ISO code</span>
<span id="cb24-58"><a href="#cb24-58" aria-hidden="true" tabindex="-1"></a>(<span class="in">`ISO_3DIGIT`</span>) rather than simulated.</span>
<span id="cb24-59"><a href="#cb24-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-60"><a href="#cb24-60" aria-hidden="true" tabindex="-1"></a><span class="in">```{r simulate-covariates}</span></span>
<span id="cb24-61"><a href="#cb24-61" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">898</span>)  <span class="co"># reproducibility</span></span>
<span id="cb24-62"><a href="#cb24-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-63"><a href="#cb24-63" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(africa_health)</span>
<span id="cb24-64"><a href="#cb24-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-65"><a href="#cb24-65" aria-hidden="true" tabindex="-1"></a>africa_health <span class="ot">&lt;-</span> africa_health <span class="sc">|&gt;</span> </span>
<span id="cb24-66"><a href="#cb24-66" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb24-67"><a href="#cb24-67" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Smoking prevalence (% of adult population) — WHO African region estimates</span></span>
<span id="cb24-68"><a href="#cb24-68" aria-hidden="true" tabindex="-1"></a>    <span class="co"># typically range ~10-25%; strongest modifiable risk factor for pancreatic cancer</span></span>
<span id="cb24-69"><a href="#cb24-69" aria-hidden="true" tabindex="-1"></a>    <span class="at">smoking_prev =</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">8</span>, <span class="at">max =</span> <span class="dv">28</span>), <span class="dv">1</span>),</span>
<span id="cb24-70"><a href="#cb24-70" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb24-71"><a href="#cb24-71" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Obesity prevalence (% adults, BMI &gt;= 30) — WHO Africa region estimates</span></span>
<span id="cb24-72"><a href="#cb24-72" aria-hidden="true" tabindex="-1"></a>    <span class="co"># range roughly 5-30% depending on urbanization/country</span></span>
<span id="cb24-73"><a href="#cb24-73" aria-hidden="true" tabindex="-1"></a>    <span class="at">obesity_prev =</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">5</span>, <span class="at">max =</span> <span class="dv">30</span>), <span class="dv">1</span>),</span>
<span id="cb24-74"><a href="#cb24-74" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb24-75"><a href="#cb24-75" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Type 2 diabetes prevalence (%) — longstanding diabetes is a well-established</span></span>
<span id="cb24-76"><a href="#cb24-76" aria-hidden="true" tabindex="-1"></a>    <span class="co"># pancreatic cancer risk factor; IDF Africa estimates ~3-10% typically</span></span>
<span id="cb24-77"><a href="#cb24-77" aria-hidden="true" tabindex="-1"></a>    <span class="at">diabetes_prev =</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">2</span>, <span class="at">max =</span> <span class="dv">11</span>), <span class="dv">1</span>),</span>
<span id="cb24-78"><a href="#cb24-78" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb24-79"><a href="#cb24-79" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Alcohol consumption (litres pure alcohol per capita per year) —</span></span>
<span id="cb24-80"><a href="#cb24-80" aria-hidden="true" tabindex="-1"></a>    <span class="co"># heavy long-term use linked to chronic pancreatitis -&gt; elevated risk</span></span>
<span id="cb24-81"><a href="#cb24-81" aria-hidden="true" tabindex="-1"></a>    <span class="at">alcohol_per_capita =</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="at">min =</span> <span class="fl">0.5</span>, <span class="at">max =</span> <span class="dv">12</span>), <span class="dv">1</span>),</span>
<span id="cb24-82"><a href="#cb24-82" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb24-83"><a href="#cb24-83" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Family history / genetic predisposition proxy (% of cases with</span></span>
<span id="cb24-84"><a href="#cb24-84" aria-hidden="true" tabindex="-1"></a>    <span class="co"># first-degree relative history) — literature suggests ~5-10% of</span></span>
<span id="cb24-85"><a href="#cb24-85" aria-hidden="true" tabindex="-1"></a>    <span class="co"># pancreatic cancers have a hereditary component</span></span>
<span id="cb24-86"><a href="#cb24-86" aria-hidden="true" tabindex="-1"></a>    <span class="at">family_history_prev =</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">3</span>, <span class="at">max =</span> <span class="dv">10</span>), <span class="dv">1</span>),</span>
<span id="cb24-87"><a href="#cb24-87" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb24-88"><a href="#cb24-88" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Urbanization (%) — proxy for dietary/lifestyle transition,</span></span>
<span id="cb24-89"><a href="#cb24-89" aria-hidden="true" tabindex="-1"></a>    <span class="co"># often used as a covariate for NCD risk in African epidemiology</span></span>
<span id="cb24-90"><a href="#cb24-90" aria-hidden="true" tabindex="-1"></a>    <span class="at">urbanization_pct =</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">15</span>, <span class="at">max =</span> <span class="dv">85</span>), <span class="dv">1</span>)</span>
<span id="cb24-91"><a href="#cb24-91" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-92"><a href="#cb24-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-93"><a href="#cb24-93" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(africa_health[<span class="fu">c</span>(<span class="st">"NAME"</span>, <span class="st">"smoking_prev"</span>, <span class="st">"obesity_prev"</span>, </span>
<span id="cb24-94"><a href="#cb24-94" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"diabetes_prev"</span>, <span class="st">"alcohol_per_capita"</span>, </span>
<span id="cb24-95"><a href="#cb24-95" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"family_history_prev"</span>, <span class="st">"urbanization_pct"</span>)])</span>
<span id="cb24-96"><a href="#cb24-96" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-97"><a href="#cb24-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-98"><a href="#cb24-98" aria-hidden="true" tabindex="-1"></a>**Key parameters:** - <span class="in">`runif(n, min, max)`</span>: draws <span class="in">`n`</span> random values from</span>
<span id="cb24-99"><a href="#cb24-99" aria-hidden="true" tabindex="-1"></a>a uniform distribution bounded to a realistic range for each covariate,</span>
<span id="cb24-100"><a href="#cb24-100" aria-hidden="true" tabindex="-1"></a>loosely based on published prevalence ranges across African countries.</span>
<span id="cb24-101"><a href="#cb24-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-102"><a href="#cb24-102" aria-hidden="true" tabindex="-1"></a>These covariates are simulated **independently of <span class="in">`incidence`</span> and of</span>
<span id="cb24-103"><a href="#cb24-103" aria-hidden="true" tabindex="-1"></a>each other** — they are not designed to correlate with pancreatic cancer</span>
<span id="cb24-104"><a href="#cb24-104" aria-hidden="true" tabindex="-1"></a>rates. This is intentional: the goal is to demonstrate the spatial</span>
<span id="cb24-105"><a href="#cb24-105" aria-hidden="true" tabindex="-1"></a>regression *pipeline* (data structure, model syntax, diagnostics), not</span>
<span id="cb24-106"><a href="#cb24-106" aria-hidden="true" tabindex="-1"></a>to produce a real epidemiological finding.</span>
<span id="cb24-107"><a href="#cb24-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-108"><a href="#cb24-108" aria-hidden="true" tabindex="-1"></a>**Expected output:** Six new columns appended to <span class="in">`africa_health`</span></span>
<span id="cb24-109"><a href="#cb24-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-110"><a href="#cb24-110" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Column <span class="pp">|</span> Description <span class="pp">|</span> Simulated range <span class="pp">|</span></span>
<span id="cb24-111"><a href="#cb24-111" aria-hidden="true" tabindex="-1"></a><span class="pp">|------------------------|------------------------|------------------------|</span></span>
<span id="cb24-112"><a href="#cb24-112" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`smoking_prev`</span> <span class="pp">|</span> Adult smoking prevalence (%) <span class="pp">|</span> 8–28% <span class="pp">|</span></span>
<span id="cb24-113"><a href="#cb24-113" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`obesity_prev`</span> <span class="pp">|</span> Adult obesity prevalence, BMI ≥ 30 (%) <span class="pp">|</span> 5–30% <span class="pp">|</span></span>
<span id="cb24-114"><a href="#cb24-114" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`diabetes_prev`</span> <span class="pp">|</span> Type 2 diabetes prevalence (%) <span class="pp">|</span> 2–11% <span class="pp">|</span></span>
<span id="cb24-115"><a href="#cb24-115" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`alcohol_per_capita`</span> <span class="pp">|</span> Alcohol consumption (litres pure alcohol/year) <span class="pp">|</span> 0.5–12 <span class="pp">|</span></span>
<span id="cb24-116"><a href="#cb24-116" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`family_history_prev`</span> <span class="pp">|</span> Cases with first-degree relative history (%) <span class="pp">|</span> 3–10% <span class="pp">|</span></span>
<span id="cb24-117"><a href="#cb24-117" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`urbanization_pct`</span> <span class="pp">|</span> Urban population (%) <span class="pp">|</span> 15–85% <span class="pp">|</span></span>
<span id="cb24-118"><a href="#cb24-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-119"><a href="#cb24-119" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb24-120"><a href="#cb24-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-121"><a href="#cb24-121" aria-hidden="true" tabindex="-1"></a><span class="fu">## Build Ordinary Least Squares (OLS) Regression {#sec-ols}</span></span>
<span id="cb24-122"><a href="#cb24-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-123"><a href="#cb24-123" aria-hidden="true" tabindex="-1"></a>**Purpose:** Establish a global (non-spatial) baseline model relating</span>
<span id="cb24-124"><a href="#cb24-124" aria-hidden="true" tabindex="-1"></a>pancreatic cancer incidence to lifestyle, genetic and demographic risk</span>
<span id="cb24-125"><a href="#cb24-125" aria-hidden="true" tabindex="-1"></a>factors.</span>
<span id="cb24-126"><a href="#cb24-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-127"><a href="#cb24-127" aria-hidden="true" tabindex="-1"></a><span class="in">```{r ols-model}</span></span>
<span id="cb24-128"><a href="#cb24-128" aria-hidden="true" tabindex="-1"></a>ols_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb24-129"><a href="#cb24-129" aria-hidden="true" tabindex="-1"></a>  incidence <span class="sc">~</span> smoking_prev <span class="sc">+</span> obesity_prev <span class="sc">+</span> diabetes_prev <span class="sc">+</span> </span>
<span id="cb24-130"><a href="#cb24-130" aria-hidden="true" tabindex="-1"></a>    alcohol_per_capita <span class="sc">+</span> family_history_prev <span class="sc">+</span> urbanization_pct <span class="sc">+</span> </span>
<span id="cb24-131"><a href="#cb24-131" aria-hidden="true" tabindex="-1"></a>    female <span class="sc">+</span> male <span class="sc">+</span> ageb <span class="sc">+</span> agec,</span>
<span id="cb24-132"><a href="#cb24-132" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> africa_health</span>
<span id="cb24-133"><a href="#cb24-133" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-134"><a href="#cb24-134" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ols_model)</span>
<span id="cb24-135"><a href="#cb24-135" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-136"><a href="#cb24-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-137"><a href="#cb24-137" aria-hidden="true" tabindex="-1"></a>**Key parameters:** - Formula syntax:</span>
<span id="cb24-138"><a href="#cb24-138" aria-hidden="true" tabindex="-1"></a><span class="in">`response ~ predictor1 + predictor2 + ...`</span> - Interpretation: Positive</span>
<span id="cb24-139"><a href="#cb24-139" aria-hidden="true" tabindex="-1"></a>coefficients indicate higher expected incidence with higher predictor</span>
<span id="cb24-140"><a href="#cb24-140" aria-hidden="true" tabindex="-1"></a>values.</span>
<span id="cb24-141"><a href="#cb24-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-142"><a href="#cb24-142" aria-hidden="true" tabindex="-1"></a>**Expected output:** A standard <span class="in">`lm`</span> summary showing coefficients,</span>
<span id="cb24-143"><a href="#cb24-143" aria-hidden="true" tabindex="-1"></a>standard errors, t-values, and p-values. R² indicates the proportion of</span>
<span id="cb24-144"><a href="#cb24-144" aria-hidden="true" tabindex="-1"></a>variance explained globally.</span>
<span id="cb24-145"><a href="#cb24-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-146"><a href="#cb24-146" aria-hidden="true" tabindex="-1"></a>This model prints a warning message. The $R^2$ value is exactly **1**</span>
<span id="cb24-147"><a href="#cb24-147" aria-hidden="true" tabindex="-1"></a>which creates room for concern. This is not a real spatial regression</span>
<span id="cb24-148"><a href="#cb24-148" aria-hidden="true" tabindex="-1"></a>breakthrough, it is a classic case of data leakage through an identity</span>
<span id="cb24-149"><a href="#cb24-149" aria-hidden="true" tabindex="-1"></a>relationship. Hence the perfect fit is a red flag not a good sign.</span>
<span id="cb24-150"><a href="#cb24-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-151"><a href="#cb24-151" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb24-152"><a href="#cb24-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-153"><a href="#cb24-153" aria-hidden="true" tabindex="-1"></a><span class="fu">## Diagnosing Data Leakage {#sec-diagnose}</span></span>
<span id="cb24-154"><a href="#cb24-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-155"><a href="#cb24-155" aria-hidden="true" tabindex="-1"></a>The first **ols** model returned <span class="in">`R-squared: 1`</span>, an F-statistic of</span>
<span id="cb24-156"><a href="#cb24-156" aria-hidden="true" tabindex="-1"></a><span class="in">`2.36e+31`</span> and an explicit warning -</span>
<span id="cb24-157"><a href="#cb24-157" aria-hidden="true" tabindex="-1"></a><span class="in">`essentialperfect fit: summary may be unreliable`</span>. A model that fits</span>
<span id="cb24-158"><a href="#cb24-158" aria-hidden="true" tabindex="-1"></a>perfectly is almost always telling you that the outcome is</span>
<span id="cb24-159"><a href="#cb24-159" aria-hidden="true" tabindex="-1"></a>mathematically derived from one or more of its own predictors. This is</span>
<span id="cb24-160"><a href="#cb24-160" aria-hidden="true" tabindex="-1"></a>called **data leakage**</span>
<span id="cb24-161"><a href="#cb24-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-162"><a href="#cb24-162" aria-hidden="true" tabindex="-1"></a>**Step 1: Inspect the coefficients.** Looking at the model summary, two</span>
<span id="cb24-163"><a href="#cb24-163" aria-hidden="true" tabindex="-1"></a>variables stood out immediately:</span>
<span id="cb24-164"><a href="#cb24-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-165"><a href="#cb24-165" aria-hidden="true" tabindex="-1"></a><span class="in">```         </span></span>
<span id="cb24-166"><a href="#cb24-166" aria-hidden="true" tabindex="-1"></a><span class="in">female   9.302e-02   t = 1.005e+13   p &lt; 2e-16</span></span>
<span id="cb24-167"><a href="#cb24-167" aria-hidden="true" tabindex="-1"></a><span class="in">male     9.302e-02   t = 1.003e+13   p &lt; 2e-16</span></span>
<span id="cb24-168"><a href="#cb24-168" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-169"><a href="#cb24-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-170"><a href="#cb24-170" aria-hidden="true" tabindex="-1"></a>Both coefficients are identical to four decimal figures, with t-value</span>
<span id="cb24-171"><a href="#cb24-171" aria-hidden="true" tabindex="-1"></a>around $10^{13}$. T-values that enormous are a signature of the model</span>
<span id="cb24-172"><a href="#cb24-172" aria-hidden="true" tabindex="-1"></a>detecting an algebraic identity not a strong effect.</span>
<span id="cb24-173"><a href="#cb24-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-174"><a href="#cb24-174" aria-hidden="true" tabindex="-1"></a>**Step 2: Test the suspected Identity directly**</span>
<span id="cb24-175"><a href="#cb24-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-176"><a href="#cb24-176" aria-hidden="true" tabindex="-1"></a><span class="in">```{r test-suspect}</span></span>
<span id="cb24-177"><a href="#cb24-177" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(africa_health<span class="sc">$</span>incidence, africa_health<span class="sc">$</span>female <span class="sc">+</span> africa_health<span class="sc">$</span>male)</span>
<span id="cb24-178"><a href="#cb24-178" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(africa_health<span class="sc">$</span>incidence <span class="sc">/</span> (africa_health<span class="sc">$</span>female <span class="sc">+</span> africa_health<span class="sc">$</span>male))</span>
<span id="cb24-179"><a href="#cb24-179" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-180"><a href="#cb24-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-181"><a href="#cb24-181" aria-hidden="true" tabindex="-1"></a>A correlation of 1 between <span class="in">`incidence`</span> and gender confirms that</span>
<span id="cb24-182"><a href="#cb24-182" aria-hidden="true" tabindex="-1"></a><span class="in">`incidence`</span> is a fixed linear function of <span class="in">`female + male`</span>. Dividing one</span>
<span id="cb24-183"><a href="#cb24-183" aria-hidden="true" tabindex="-1"></a>by the other reveals the exact relationship. Every single country</span>
<span id="cb24-184"><a href="#cb24-184" aria-hidden="true" tabindex="-1"></a>returns the exact constant <span class="in">`0.09302326`</span>, meaning <span class="in">`incidence`</span> was</span>
<span id="cb24-185"><a href="#cb24-185" aria-hidden="true" tabindex="-1"></a>computed directly from <span class="in">`male`</span> and <span class="in">`female`</span> (or they share a common</span>
<span id="cb24-186"><a href="#cb24-186" aria-hidden="true" tabindex="-1"></a>upstream calculation)</span>
<span id="cb24-187"><a href="#cb24-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-188"><a href="#cb24-188" aria-hidden="true" tabindex="-1"></a>Including <span class="in">`male`</span> and <span class="in">`female`</span> as predictors makes it **mathematically</span>
<span id="cb24-189"><a href="#cb24-189" aria-hidden="true" tabindex="-1"></a>circular**, the model is not learning but rather reversing an arithmetic</span>
<span id="cb24-190"><a href="#cb24-190" aria-hidden="true" tabindex="-1"></a>formula.</span>
<span id="cb24-191"><a href="#cb24-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-192"><a href="#cb24-192" aria-hidden="true" tabindex="-1"></a>**Step 3: Screen every numeric variable for leakage**</span>
<span id="cb24-193"><a href="#cb24-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-194"><a href="#cb24-194" aria-hidden="true" tabindex="-1"></a><span class="in">```{r check-cor}</span></span>
<span id="cb24-195"><a href="#cb24-195" aria-hidden="true" tabindex="-1"></a><span class="co"># Check all numeric columns systematically against incidence</span></span>
<span id="cb24-196"><a href="#cb24-196" aria-hidden="true" tabindex="-1"></a>numeric_cols <span class="ot">&lt;-</span> africa_health <span class="sc">|&gt;</span> </span>
<span id="cb24-197"><a href="#cb24-197" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span>                    <span class="co"># drop geometry — not numeric</span></span>
<span id="cb24-198"><a href="#cb24-198" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">|&gt;</span> </span>
<span id="cb24-199"><a href="#cb24-199" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>incidence) <span class="sc">|&gt;</span>                    <span class="co"># exclude the outcome itself</span></span>
<span id="cb24-200"><a href="#cb24-200" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>()</span>
<span id="cb24-201"><a href="#cb24-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-202"><a href="#cb24-202" aria-hidden="true" tabindex="-1"></a>cor_check <span class="ot">&lt;-</span> <span class="fu">sapply</span>(numeric_cols, <span class="cf">function</span>(col) {</span>
<span id="cb24-203"><a href="#cb24-203" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(africa_health<span class="sc">$</span>incidence, africa_health[[col]], <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb24-204"><a href="#cb24-204" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb24-205"><a href="#cb24-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-206"><a href="#cb24-206" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">abs</span>(cor_check), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-207"><a href="#cb24-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-208"><a href="#cb24-208" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-209"><a href="#cb24-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-210"><a href="#cb24-210" aria-hidden="true" tabindex="-1"></a>The output shows the leakage extends well beyond <span class="in">`female`</span>/<span class="in">`male`</span>. Almost</span>
<span id="cb24-211"><a href="#cb24-211" aria-hidden="true" tabindex="-1"></a>every variable with <span class="in">`|r|&gt;0.85`</span> shares a consistent naming pattern:</span>
<span id="cb24-212"><a href="#cb24-212" aria-hidden="true" tabindex="-1"></a>age-banded (<span class="in">`age*`</span>), year-indexed (<span class="in">`yr*`</span>) and male/female-stratified</span>
<span id="cb24-213"><a href="#cb24-213" aria-hidden="true" tabindex="-1"></a>(<span class="in">`m*`</span>/<span class="in">`f*`</span>). This strongly indicates they are all components of the same</span>
<span id="cb24-214"><a href="#cb24-214" aria-hidden="true" tabindex="-1"></a>underlying case-count calculation that produced <span class="in">`incidence`</span>.</span>
<span id="cb24-215"><a href="#cb24-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-216"><a href="#cb24-216" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb24-217"><a href="#cb24-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-218"><a href="#cb24-218" aria-hidden="true" tabindex="-1"></a><span class="fu">## Refined Model {#sec-ols-refine}</span></span>
<span id="cb24-219"><a href="#cb24-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-220"><a href="#cb24-220" aria-hidden="true" tabindex="-1"></a>Based on the correlation screen, we exclude every variable structurally</span>
<span id="cb24-221"><a href="#cb24-221" aria-hidden="true" tabindex="-1"></a>tied to incidence calculation along with the non-informative row</span>
<span id="cb24-222"><a href="#cb24-222" aria-hidden="true" tabindex="-1"></a>identifier. In their place we retain our six simulated risk-factor</span>
<span id="cb24-223"><a href="#cb24-223" aria-hidden="true" tabindex="-1"></a>covariates.</span>
<span id="cb24-224"><a href="#cb24-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-225"><a href="#cb24-225" aria-hidden="true" tabindex="-1"></a>Another thing worth mentioning in epidemiology is the raw incidence</span>
<span id="cb24-226"><a href="#cb24-226" aria-hidden="true" tabindex="-1"></a>counts. We rarely run models on raw count data. Instead we will</span>
<span id="cb24-227"><a href="#cb24-227" aria-hidden="true" tabindex="-1"></a>calculate an **incidence rate** (e.g cases per 100,000 people) before</span>
<span id="cb24-228"><a href="#cb24-228" aria-hidden="true" tabindex="-1"></a>modelling.</span>
<span id="cb24-229"><a href="#cb24-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-230"><a href="#cb24-230" aria-hidden="true" tabindex="-1"></a><span class="in">```{r refined-ols}</span></span>
<span id="cb24-231"><a href="#cb24-231" aria-hidden="true" tabindex="-1"></a>africa_health <span class="ot">&lt;-</span> africa_health <span class="sc">|&gt;</span> </span>
<span id="cb24-232"><a href="#cb24-232" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">incidence_rate =</span> (incidence<span class="sc">/</span>TOTPOP)<span class="sc">*</span><span class="dv">100000</span>)</span>
<span id="cb24-233"><a href="#cb24-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-234"><a href="#cb24-234" aria-hidden="true" tabindex="-1"></a>ols_refined <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb24-235"><a href="#cb24-235" aria-hidden="true" tabindex="-1"></a>  incidence_rate <span class="sc">~</span> smoking_prev <span class="sc">+</span> obesity_prev <span class="sc">+</span> diabetes_prev <span class="sc">+</span> </span>
<span id="cb24-236"><a href="#cb24-236" aria-hidden="true" tabindex="-1"></a>    alcohol_per_capita <span class="sc">+</span> family_history_prev <span class="sc">+</span> urbanization_pct,</span>
<span id="cb24-237"><a href="#cb24-237" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> africa_health</span>
<span id="cb24-238"><a href="#cb24-238" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-239"><a href="#cb24-239" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ols_refined)</span>
<span id="cb24-240"><a href="#cb24-240" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-241"><a href="#cb24-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-242"><a href="#cb24-242" aria-hidden="true" tabindex="-1"></a>This output provides an overall statistically insignificant model.</span>
<span id="cb24-243"><a href="#cb24-243" aria-hidden="true" tabindex="-1"></a>Because the simulated covariates were generated purely as random noise</span>
<span id="cb24-244"><a href="#cb24-244" aria-hidden="true" tabindex="-1"></a>(<span class="in">`runif`</span>), the OLS model did exactly what it is supposed to do. It shows</span>
<span id="cb24-245"><a href="#cb24-245" aria-hidden="true" tabindex="-1"></a>no statistical relationship between these covariates and the target</span>
<span id="cb24-246"><a href="#cb24-246" aria-hidden="true" tabindex="-1"></a>variable.</span>
<span id="cb24-247"><a href="#cb24-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-248"><a href="#cb24-248" aria-hidden="true" tabindex="-1"></a>Although all the covariates are randomly generated, <span class="in">`obesity_prev`</span> and</span>
<span id="cb24-249"><a href="#cb24-249" aria-hidden="true" tabindex="-1"></a><span class="in">`urbanization_pct`</span> are showing marginal significance. This is purely by</span>
<span id="cb24-250"><a href="#cb24-250" aria-hidden="true" tabindex="-1"></a>chance because we can confirm from their estimate direction (<span class="in">`-0.103`</span></span>
<span id="cb24-251"><a href="#cb24-251" aria-hidden="true" tabindex="-1"></a>and <span class="in">`-0.041`</span>) that the math contradicts the biology; higher obesity and</span>
<span id="cb24-252"><a href="#cb24-252" aria-hidden="true" tabindex="-1"></a>urbanisation should increase pancreatic cancer risk.</span>
<span id="cb24-253"><a href="#cb24-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-254"><a href="#cb24-254" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb24-255"><a href="#cb24-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-256"><a href="#cb24-256" aria-hidden="true" tabindex="-1"></a><span class="fu">## Test for Spatial Residual Autocorrelation {#sec-residual-moran}</span></span>
<span id="cb24-257"><a href="#cb24-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-258"><a href="#cb24-258" aria-hidden="true" tabindex="-1"></a>**Purpose:** Check whether the OLS model's residuals are spatially</span>
<span id="cb24-259"><a href="#cb24-259" aria-hidden="true" tabindex="-1"></a>random. The core assumption of OLS is that its errors (residuals) are</span>
<span id="cb24-260"><a href="#cb24-260" aria-hidden="true" tabindex="-1"></a>randomly distributed. If significant autocorrelation remains, OLS</span>
<span id="cb24-261"><a href="#cb24-261" aria-hidden="true" tabindex="-1"></a>standard errors are biased and a spatial model (or GWR) is needed.</span>
<span id="cb24-262"><a href="#cb24-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-263"><a href="#cb24-263" aria-hidden="true" tabindex="-1"></a>In spatial epidemiology, if our model is missing a key geographical</span>
<span id="cb24-264"><a href="#cb24-264" aria-hidden="true" tabindex="-1"></a>variable, the model's error will cluster together geographically. This</span>
<span id="cb24-265"><a href="#cb24-265" aria-hidden="true" tabindex="-1"></a>is called **Spatial Autocorrelation of Residuals**</span>
<span id="cb24-266"><a href="#cb24-266" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-267"><a href="#cb24-267" aria-hidden="true" tabindex="-1"></a><span class="in">```{r moran-residuals}</span></span>
<span id="cb24-268"><a href="#cb24-268" aria-hidden="true" tabindex="-1"></a>residual_moran <span class="ot">&lt;-</span> <span class="fu">lm.morantest</span>(</span>
<span id="cb24-269"><a href="#cb24-269" aria-hidden="true" tabindex="-1"></a>  <span class="at">model =</span> ols_refined,</span>
<span id="cb24-270"><a href="#cb24-270" aria-hidden="true" tabindex="-1"></a>  <span class="at">listw =</span> lw,</span>
<span id="cb24-271"><a href="#cb24-271" aria-hidden="true" tabindex="-1"></a>  <span class="at">zero.policy =</span> <span class="cn">TRUE</span></span>
<span id="cb24-272"><a href="#cb24-272" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-273"><a href="#cb24-273" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(residual_moran)</span>
<span id="cb24-274"><a href="#cb24-274" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-275"><a href="#cb24-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-276"><a href="#cb24-276" aria-hidden="true" tabindex="-1"></a>**Key parameters:** - <span class="in">`lm.morantest()`</span>: Applies Moran's I to the</span>
<span id="cb24-277"><a href="#cb24-277" aria-hidden="true" tabindex="-1"></a>regression residuals rather than the raw outcome.</span>
<span id="cb24-278"><a href="#cb24-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-279"><a href="#cb24-279" aria-hidden="true" tabindex="-1"></a>**Expected output:** - If p <span class="sc">\&lt;</span> 0.05, residuals are spatially</span>
<span id="cb24-280"><a href="#cb24-280" aria-hidden="true" tabindex="-1"></a>autocorrelated → OLS is misspecified, therefore a spatial model (like</span>
<span id="cb24-281"><a href="#cb24-281" aria-hidden="true" tabindex="-1"></a>GWR) is required. - If p <span class="sc">\&gt;</span> 0.05, OLS residuals are spatially random</span>
<span id="cb24-282"><a href="#cb24-282" aria-hidden="true" tabindex="-1"></a>(rare in epidemiology).</span>
<span id="cb24-283"><a href="#cb24-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-284"><a href="#cb24-284" aria-hidden="true" tabindex="-1"></a>The Null hypothesis for this test is that the residuals are randomly</span>
<span id="cb24-285"><a href="#cb24-285" aria-hidden="true" tabindex="-1"></a>distributed (no spatial autocorrelation). Because our p-vale is high, we</span>
<span id="cb24-286"><a href="#cb24-286" aria-hidden="true" tabindex="-1"></a>conclude that the errors in the model are randomly distributed across</span>
<span id="cb24-287"><a href="#cb24-287" aria-hidden="true" tabindex="-1"></a>the African continent. There is no statistically significant spatial</span>
<span id="cb24-288"><a href="#cb24-288" aria-hidden="true" tabindex="-1"></a>autocorrelation in the residuals.</span>
<span id="cb24-289"><a href="#cb24-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-290"><a href="#cb24-290" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb24-291"><a href="#cb24-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-292"><a href="#cb24-292" aria-hidden="true" tabindex="-1"></a><span class="fu">## Geographically Weighted Regression (GWR) {#sec-gwr}</span></span>
<span id="cb24-293"><a href="#cb24-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-294"><a href="#cb24-294" aria-hidden="true" tabindex="-1"></a>**Purpose:** Fit local regression models that allow the relationship</span>
<span id="cb24-295"><a href="#cb24-295" aria-hidden="true" tabindex="-1"></a>between cancer and lifestyle/genetic risk factors to vary across space</span>
<span id="cb24-296"><a href="#cb24-296" aria-hidden="true" tabindex="-1"></a>(spatial non-stationarity).</span>
<span id="cb24-297"><a href="#cb24-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-298"><a href="#cb24-298" aria-hidden="true" tabindex="-1"></a><span class="in">```{r gwr-model}</span></span>
<span id="cb24-299"><a href="#cb24-299" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Find optimal adaptive bandwidth (number of nearest neighbours)</span></span>
<span id="cb24-300"><a href="#cb24-300" aria-hidden="true" tabindex="-1"></a><span class="co"># This uses cross-validation to find best fit</span></span>
<span id="cb24-301"><a href="#cb24-301" aria-hidden="true" tabindex="-1"></a>bw_adapt <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(</span>
<span id="cb24-302"><a href="#cb24-302" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> incidence_rate <span class="sc">~</span> smoking_prev <span class="sc">+</span> obesity_prev <span class="sc">+</span> </span>
<span id="cb24-303"><a href="#cb24-303" aria-hidden="true" tabindex="-1"></a>    diabetes_prev <span class="sc">+</span> alcohol_per_capita <span class="sc">+</span> </span>
<span id="cb24-304"><a href="#cb24-304" aria-hidden="true" tabindex="-1"></a>    family_history_prev <span class="sc">+</span> urbanization_pct,</span>
<span id="cb24-305"><a href="#cb24-305" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> africa_health,</span>
<span id="cb24-306"><a href="#cb24-306" aria-hidden="true" tabindex="-1"></a>  <span class="at">approach =</span> <span class="st">"CV"</span>,     <span class="co"># Cross-validation approach</span></span>
<span id="cb24-307"><a href="#cb24-307" aria-hidden="true" tabindex="-1"></a>  <span class="at">kernel =</span> <span class="st">"bisquare"</span>, <span class="co"># the shape of the spatial weight decay</span></span>
<span id="cb24-308"><a href="#cb24-308" aria-hidden="true" tabindex="-1"></a>  <span class="at">adaptive =</span> <span class="cn">TRUE</span>      <span class="co"># TRUE=find optimal no. of neigbours. FALSE = find distance</span></span>
<span id="cb24-309"><a href="#cb24-309" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-310"><a href="#cb24-310" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Optimal adaptive bandwidth:"</span>, bw_adapt, <span class="st">"neighbors</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb24-311"><a href="#cb24-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-312"><a href="#cb24-312" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Fit GWR model</span></span>
<span id="cb24-313"><a href="#cb24-313" aria-hidden="true" tabindex="-1"></a>gwr_model <span class="ot">&lt;-</span> <span class="fu">gwr.basic</span>(</span>
<span id="cb24-314"><a href="#cb24-314" aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> incidence_rate <span class="sc">~</span> smoking_prev <span class="sc">+</span> obesity_prev <span class="sc">+</span> </span>
<span id="cb24-315"><a href="#cb24-315" aria-hidden="true" tabindex="-1"></a>    diabetes_prev <span class="sc">+</span> alcohol_per_capita <span class="sc">+</span> </span>
<span id="cb24-316"><a href="#cb24-316" aria-hidden="true" tabindex="-1"></a>    family_history_prev <span class="sc">+</span> urbanization_pct,</span>
<span id="cb24-317"><a href="#cb24-317" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> africa_health,</span>
<span id="cb24-318"><a href="#cb24-318" aria-hidden="true" tabindex="-1"></a>  <span class="at">bw =</span> bw_adapt,</span>
<span id="cb24-319"><a href="#cb24-319" aria-hidden="true" tabindex="-1"></a>  <span class="at">kernel =</span> <span class="st">"bisquare"</span>,</span>
<span id="cb24-320"><a href="#cb24-320" aria-hidden="true" tabindex="-1"></a>  <span class="at">adaptive =</span> <span class="cn">TRUE</span>,</span>
<span id="cb24-321"><a href="#cb24-321" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-322"><a href="#cb24-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-323"><a href="#cb24-323" aria-hidden="true" tabindex="-1"></a><span class="co"># Print summary (includes global OLS + local GWR diagnostics)</span></span>
<span id="cb24-324"><a href="#cb24-324" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(gwr_model)</span>
<span id="cb24-325"><a href="#cb24-325" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-326"><a href="#cb24-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-327"><a href="#cb24-327" aria-hidden="true" tabindex="-1"></a>**Key parameters:** - <span class="in">`bw.gwr()`</span>: <span class="in">`adaptive = TRUE`</span> finds a bandwidth in</span>
<span id="cb24-328"><a href="#cb24-328" aria-hidden="true" tabindex="-1"></a>number of neighbours rather than distance units. Better for irregularly</span>
<span id="cb24-329"><a href="#cb24-329" aria-hidden="true" tabindex="-1"></a>sized polygons. - <span class="in">`kernel = "bisquare"`</span>: Weights drop to zero beyond the</span>
<span id="cb24-330"><a href="#cb24-330" aria-hidden="true" tabindex="-1"></a>bandwidth, creating clean local windows. - <span class="in">`gwr.basic()`</span>: Fits a</span>
<span id="cb24-331"><a href="#cb24-331" aria-hidden="true" tabindex="-1"></a>separate weighted OLS at every polygon centroid.</span>
<span id="cb24-332"><a href="#cb24-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-333"><a href="#cb24-333" aria-hidden="true" tabindex="-1"></a>**Expected output:** - Bandwidth value (gave 35 neighbours for</span>
<span id="cb24-334"><a href="#cb24-334" aria-hidden="true" tabindex="-1"></a>country-level Africa data). - GWR diagnostics showing local R²,</span>
<span id="cb24-335"><a href="#cb24-335" aria-hidden="true" tabindex="-1"></a>coefficient ranges, and AICc values vs global OLS.</span>
<span id="cb24-336"><a href="#cb24-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-337"><a href="#cb24-337" aria-hidden="true" tabindex="-1"></a>A bandwidth of 35 is huge for a spatial region of 54 countries. The</span>
<span id="cb24-338"><a href="#cb24-338" aria-hidden="true" tabindex="-1"></a>model is forced to look at over half a continent to make a single</span>
<span id="cb24-339"><a href="#cb24-339" aria-hidden="true" tabindex="-1"></a>prediction. The GWR coefficient estimates are given as a range because</span>
<span id="cb24-340"><a href="#cb24-340" aria-hidden="true" tabindex="-1"></a>it changes depending on where you are on the map. In the global OLS the</span>
<span id="cb24-341"><a href="#cb24-341" aria-hidden="true" tabindex="-1"></a>relationship for <span class="in">`diabetes_pev`</span> is negative but GWR reveals that it</span>
<span id="cb24-342"><a href="#cb24-342" aria-hidden="true" tabindex="-1"></a>changes in some part of the continent (<span class="in">`min:-0.543`</span> and <span class="in">`max:0.225`</span>).</span>
<span id="cb24-343"><a href="#cb24-343" aria-hidden="true" tabindex="-1"></a>This shows the relationship is unstable across space (But remember this</span>
<span id="cb24-344"><a href="#cb24-344" aria-hidden="true" tabindex="-1"></a>is simulated data so the model is just chasing random noise).</span>
<span id="cb24-345"><a href="#cb24-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-346"><a href="#cb24-346" aria-hidden="true" tabindex="-1"></a>The GWR $R^2$ looks very high but that should not be the metric of</span>
<span id="cb24-347"><a href="#cb24-347" aria-hidden="true" tabindex="-1"></a>interest because it is almost always high for GWR analysis. The</span>
<span id="cb24-348"><a href="#cb24-348" aria-hidden="true" tabindex="-1"></a>parameter of interest is the AICc (Lower is better). Even the the GWR</span>
<span id="cb24-349"><a href="#cb24-349" aria-hidden="true" tabindex="-1"></a>artificially inflated the $R^2$, the AICc actually went up from 276.4 in</span>
<span id="cb24-350"><a href="#cb24-350" aria-hidden="true" tabindex="-1"></a>the OLS to 294.7, this tells us that the GWR model is statistically</span>
<span id="cb24-351"><a href="#cb24-351" aria-hidden="true" tabindex="-1"></a>worse. The OLS errors were randomly distributed and so the GWR was</span>
<span id="cb24-352"><a href="#cb24-352" aria-hidden="true" tabindex="-1"></a>completely unnecessary.</span>
<span id="cb24-353"><a href="#cb24-353" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-354"><a href="#cb24-354" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb24-355"><a href="#cb24-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-356"><a href="#cb24-356" aria-hidden="true" tabindex="-1"></a><span class="fu">## Interpret and Visualize GWR Results {#sec-gwr-viz}</span></span>
<span id="cb24-357"><a href="#cb24-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-358"><a href="#cb24-358" aria-hidden="true" tabindex="-1"></a>**Purpose:** Map local coefficient surfaces to see **where** each</span>
<span id="cb24-359"><a href="#cb24-359" aria-hidden="true" tabindex="-1"></a>predictor matters most.</span>
<span id="cb24-360"><a href="#cb24-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-361"><a href="#cb24-361" aria-hidden="true" tabindex="-1"></a><span class="in">```{r gwr-maps}</span></span>
<span id="cb24-362"><a href="#cb24-362" aria-hidden="true" tabindex="-1"></a><span class="co"># gwr_model$SDF is an sf object containing local coefficients</span></span>
<span id="cb24-363"><a href="#cb24-363" aria-hidden="true" tabindex="-1"></a>gwr_sf <span class="ot">&lt;-</span> gwr_model<span class="sc">$</span>SDF</span>
<span id="cb24-364"><a href="#cb24-364" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-365"><a href="#cb24-365" aria-hidden="true" tabindex="-1"></a><span class="co"># Map the spatially varying coefficient for diabetes</span></span>
<span id="cb24-366"><a href="#cb24-366" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(gwr_sf) <span class="sc">+</span></span>
<span id="cb24-367"><a href="#cb24-367" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(</span>
<span id="cb24-368"><a href="#cb24-368" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"diabetes_prev"</span>,</span>
<span id="cb24-369"><a href="#cb24-369" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill.scale =</span> <span class="fu">tm_scale_continuous</span>(</span>
<span id="cb24-370"><a href="#cb24-370" aria-hidden="true" tabindex="-1"></a>      <span class="at">values =</span> <span class="st">"-brewer.rd_bu"</span>,     <span class="co"># Negative RdBu puts red at positive and Blue at negative</span></span>
<span id="cb24-371"><a href="#cb24-371" aria-hidden="true" tabindex="-1"></a>      <span class="at">midpoint =</span> <span class="dv">0</span>          <span class="co"># Forces the white/neutral color to sit exactly at zero</span></span>
<span id="cb24-372"><a href="#cb24-372" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb24-373"><a href="#cb24-373" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Local Coefficient</span><span class="sc">\n</span><span class="st">(Diabetes)"</span>),</span>
<span id="cb24-374"><a href="#cb24-374" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> <span class="st">'black'</span>,</span>
<span id="cb24-375"><a href="#cb24-375" aria-hidden="true" tabindex="-1"></a>    <span class="at">col_alpha =</span> <span class="fl">0.5</span>,        </span>
<span id="cb24-376"><a href="#cb24-376" aria-hidden="true" tabindex="-1"></a>    <span class="at">lwd =</span> <span class="fl">0.5</span>               </span>
<span id="cb24-377"><a href="#cb24-377" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb24-378"><a href="#cb24-378" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_title</span>(<span class="st">"GWR: Spatially Varying Effect of Diabetes"</span>)</span>
<span id="cb24-379"><a href="#cb24-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-380"><a href="#cb24-380" aria-hidden="true" tabindex="-1"></a><span class="co"># Map the local model fit (Local R-squared)</span></span>
<span id="cb24-381"><a href="#cb24-381" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(gwr_sf) <span class="sc">+</span></span>
<span id="cb24-382"><a href="#cb24-382" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(</span>
<span id="cb24-383"><a href="#cb24-383" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Local_R2"</span>,</span>
<span id="cb24-384"><a href="#cb24-384" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill.scale =</span> <span class="fu">tm_scale_continuous</span>(</span>
<span id="cb24-385"><a href="#cb24-385" aria-hidden="true" tabindex="-1"></a>      <span class="at">values =</span> <span class="st">"viridis"</span></span>
<span id="cb24-386"><a href="#cb24-386" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb24-387"><a href="#cb24-387" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill.legend =</span> <span class="fu">tm_legend</span>(<span class="at">title =</span> <span class="st">"Local R-Squared"</span>),</span>
<span id="cb24-388"><a href="#cb24-388" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> <span class="st">"black"</span>,</span>
<span id="cb24-389"><a href="#cb24-389" aria-hidden="true" tabindex="-1"></a>    <span class="at">lwd =</span> <span class="fl">0.5</span></span>
<span id="cb24-390"><a href="#cb24-390" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb24-391"><a href="#cb24-391" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_title</span>(<span class="st">"GWR: Local Model Performance across Africa"</span>)</span>
<span id="cb24-392"><a href="#cb24-392" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-393"><a href="#cb24-393" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb24-394"><a href="#cb24-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-395"><a href="#cb24-395" aria-hidden="true" tabindex="-1"></a>**Key parameters:** - <span class="in">`midpoint = 0`</span> in</span>
<span id="cb24-396"><a href="#cb24-396" aria-hidden="true" tabindex="-1"></a><span class="in">`fill.scale = tm_scale_continuous()`</span> centers the colour scale at zero,</span>
<span id="cb24-397"><a href="#cb24-397" aria-hidden="true" tabindex="-1"></a>making positive (red) and negative (blue) effects immediately visible.</span>
<span id="cb24-398"><a href="#cb24-398" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-399"><a href="#cb24-399" aria-hidden="true" tabindex="-1"></a>**Expected output:** Two maps; one showing spatially varying coefficient</span>
<span id="cb24-400"><a href="#cb24-400" aria-hidden="true" tabindex="-1"></a><span class="in">`diabetes_prev`</span> and the other showing the the area where the GWR model</span>
<span id="cb24-401"><a href="#cb24-401" aria-hidden="true" tabindex="-1"></a>performs best (<span class="in">`Local R2`</span>). Areas with red indicate a positive local</span>
<span id="cb24-402"><a href="#cb24-402" aria-hidden="true" tabindex="-1"></a>association; blue indicates a negative local association for the</span>
<span id="cb24-403"><a href="#cb24-403" aria-hidden="true" tabindex="-1"></a><span class="in">`diabetes_prev`</span> .</span>
<span id="cb24-404"><a href="#cb24-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-405"><a href="#cb24-405" aria-hidden="true" tabindex="-1"></a>The spatial variation map shows smooth colour transitions across</span>
<span id="cb24-406"><a href="#cb24-406" aria-hidden="true" tabindex="-1"></a>borders. Whiles this creates a beautiful map, remember our **AICc**</span>
<span id="cb24-407"><a href="#cb24-407" aria-hidden="true" tabindex="-1"></a>score. Because the underlying data is purely random noise, this map is</span>
<span id="cb24-408"><a href="#cb24-408" aria-hidden="true" tabindex="-1"></a>just a visualisation of the GWR algorithm 'forcing' a spatial pattern</span>
<span id="cb24-409"><a href="#cb24-409" aria-hidden="true" tabindex="-1"></a>where none actually exists.</span>
<span id="cb24-410"><a href="#cb24-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-411"><a href="#cb24-411" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------</span>
<span id="cb24-412"><a href="#cb24-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-413"><a href="#cb24-413" aria-hidden="true" tabindex="-1"></a><span class="fu">## Module 4 Checklist {#sec-m4-check .unnumbered}</span></span>
<span id="cb24-414"><a href="#cb24-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-415"><a href="#cb24-415" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[ ]</span> Extracted environmental covariates from raster data</span>
<span id="cb24-416"><a href="#cb24-416" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[ ]</span> Built and interpreted an OLS regression model</span>
<span id="cb24-417"><a href="#cb24-417" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[ ]</span> Tested OLS residuals for spatial autocorrelation</span>
<span id="cb24-418"><a href="#cb24-418" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[ ]</span> Fitted a GWR model with adaptive bandwidth</span>
<span id="cb24-419"><a href="#cb24-419" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="va">[ ]</span> Mapped local coefficient surfaces</span>
<span id="cb24-420"><a href="#cb24-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-421"><a href="#cb24-421" aria-hidden="true" tabindex="-1"></a>**Next:** Proceed to [Module 5: Machine Learning for Spatial</span>
<span id="cb24-422"><a href="#cb24-422" aria-hidden="true" tabindex="-1"></a>Epidemiology](05-ml.qmd).</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2026, George K. Agyen</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Thisbook was built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>